version: '3.1'
services:

    postgis:
        image: postgis/postgis
        container_name: postgis
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: mysecretpassword
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - pgnetwork

    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: user@domain.com
            PGADMIN_DEFAULT_PASSWORD: SuperSecret
        networks:
            - pgnetwork
        links:
            - postgis

volumes:
  pgdata:

networks:
  pgnetwork:
    driver: bridge